# Install script for directory: C:/Development/op3d_active/opencv-4.1.0/modules

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "C:/Development/op3d_active/opencv-4.1.0/msvc/install")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xlicensesx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/etc/licenses" TYPE FILE RENAME "ffmpeg-license.txt" FILES "C:/Development/op3d_active/opencv-4.1.0/3rdparty/ffmpeg/license.txt")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xlicensesx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/etc/licenses" TYPE FILE RENAME "ffmpeg-readme.txt" FILES "C:/Development/op3d_active/opencv-4.1.0/3rdparty/ffmpeg/readme.txt")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("C:/Development/op3d_active/opencv-4.1.0/msvc/modules/.firstpass/calib3d/cmake_install.cmake")
  include("C:/Development/op3d_active/opencv-4.1.0/msvc/modules/.firstpass/core/cmake_install.cmake")
  include("C:/Development/op3d_active/opencv-4.1.0/msvc/modules/.firstpass/cudev/cmake_install.cmake")
  include("C:/Development/op3d_active/opencv-4.1.0/msvc/modules/.firstpass/dnn/cmake_install.cmake")
  include("C:/Development/op3d_active/opencv-4.1.0/msvc/modules/.firstpass/features2d/cmake_install.cmake")
  include("C:/Development/op3d_active/opencv-4.1.0/msvc/modules/.firstpass/flann/cmake_install.cmake")
  include("C:/Development/op3d_active/opencv-4.1.0/msvc/modules/.firstpass/gapi/cmake_install.cmake")
  include("C:/Development/op3d_active/opencv-4.1.0/msvc/modules/.firstpass/highgui/cmake_install.cmake")
  include("C:/Development/op3d_active/opencv-4.1.0/msvc/modules/.firstpass/imgcodecs/cmake_install.cmake")
  include("C:/Development/op3d_active/opencv-4.1.0/msvc/modules/.firstpass/imgproc/cmake_install.cmake")
  include("C:/Development/op3d_active/opencv-4.1.0/msvc/modules/.firstpass/java/cmake_install.cmake")
  include("C:/Development/op3d_active/opencv-4.1.0/msvc/modules/.firstpass/js/cmake_install.cmake")
  include("C:/Development/op3d_active/opencv-4.1.0/msvc/modules/.firstpass/ml/cmake_install.cmake")
  include("C:/Development/op3d_active/opencv-4.1.0/msvc/modules/.firstpass/objdetect/cmake_install.cmake")
  include("C:/Development/op3d_active/opencv-4.1.0/msvc/modules/.firstpass/photo/cmake_install.cmake")
  include("C:/Development/op3d_active/opencv-4.1.0/msvc/modules/.firstpass/python/cmake_install.cmake")
  include("C:/Development/op3d_active/opencv-4.1.0/msvc/modules/.firstpass/stitching/cmake_install.cmake")
  include("C:/Development/op3d_active/opencv-4.1.0/msvc/modules/.firstpass/ts/cmake_install.cmake")
  include("C:/Development/op3d_active/opencv-4.1.0/msvc/modules/.firstpass/video/cmake_install.cmake")
  include("C:/Development/op3d_active/opencv-4.1.0/msvc/modules/.firstpass/videoio/cmake_install.cmake")
  include("C:/Development/op3d_active/opencv-4.1.0/msvc/modules/.firstpass/world/cmake_install.cmake")
  include("C:/Development/op3d_active/opencv-4.1.0/msvc/modules/cudev/cmake_install.cmake")
  include("C:/Development/op3d_active/opencv-4.1.0/msvc/modules/java_bindings_generator/cmake_install.cmake")
  include("C:/Development/op3d_active/opencv-4.1.0/msvc/modules/python_tests/cmake_install.cmake")
  include("C:/Development/op3d_active/opencv-4.1.0/msvc/modules/core/cmake_install.cmake")
  include("C:/Development/op3d_active/opencv-4.1.0/msvc/modules/flann/cmake_install.cmake")
  include("C:/Development/op3d_active/opencv-4.1.0/msvc/modules/imgproc/cmake_install.cmake")
  include("C:/Development/op3d_active/opencv-4.1.0/msvc/modules/ml/cmake_install.cmake")
  include("C:/Development/op3d_active/opencv-4.1.0/msvc/modules/photo/cmake_install.cmake")
  include("C:/Development/op3d_active/opencv-4.1.0/msvc/modules/dnn/cmake_install.cmake")
  include("C:/Development/op3d_active/opencv-4.1.0/msvc/modules/features2d/cmake_install.cmake")
  include("C:/Development/op3d_active/opencv-4.1.0/msvc/modules/imgcodecs/cmake_install.cmake")
  include("C:/Development/op3d_active/opencv-4.1.0/msvc/modules/videoio/cmake_install.cmake")
  include("C:/Development/op3d_active/opencv-4.1.0/msvc/modules/calib3d/cmake_install.cmake")
  include("C:/Development/op3d_active/opencv-4.1.0/msvc/modules/highgui/cmake_install.cmake")
  include("C:/Development/op3d_active/opencv-4.1.0/msvc/modules/objdetect/cmake_install.cmake")
  include("C:/Development/op3d_active/opencv-4.1.0/msvc/modules/stitching/cmake_install.cmake")
  include("C:/Development/op3d_active/opencv-4.1.0/msvc/modules/ts/cmake_install.cmake")
  include("C:/Development/op3d_active/opencv-4.1.0/msvc/modules/video/cmake_install.cmake")
  include("C:/Development/op3d_active/opencv-4.1.0/msvc/modules/java/cmake_install.cmake")
  include("C:/Development/op3d_active/opencv-4.1.0/msvc/modules/python_bindings_generator/cmake_install.cmake")

endif()

